---
- name: Provision EC2 instance
  hosts: localhost
  vars:
      region:   us-west-2
      ami:      ami-0fcf52bcf5db7b003
      set_dns:  False
      instance: t2.micro
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance
      ec2:
        keypair: Devops
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        instance_type: "{{ instance }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        group: public-ssh-sg
        wait: yes
        count: 1
        instance_tags:
           Name: NginxDemo
           exact_count: 1
        count_tag:
           Name: NginxDemo
           exact_count: 1
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }}
                    groupname=launched  
                    ansible_user=ubuntu 
                    ansible_become=yes
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_ip }}
                    port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"


- name: Configure EC2 instance in launched group
  hosts: launched
  become: True
  gather_facts: no
  tasks:
    - ping:
    - name: install web server
      package:
        name: nginx
        state: present
